### ISSUE TITLE
demo 的代码有参考的文章吗

### ISSUE THREAD

**Issue by shenxin-karl** [AirGuanZ/AtmosphereRenderer#3]
大佬你好, 请问 demo 中的代码有参考的出处吗?
 非常想学习您的代码, 但是有许多 lut 生成的代码看不明白, 其中论文也没提到
感谢你把demo开源, 祝你好运

**Comment by AirGuanZ** [comment]
LUT的定义参考[这里](https://airguanz.github.io/2021/06/11/atmosphere-rendering.html)，具体代码基本是用蒙特卡洛方法对其式子进行估值。具体哪个式子不太清楚的话，可以在这里问问

**Comment by shenxin-karl** [comment]
非常感谢你的回复
